name: firebase_auth_youtube
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  http: ^1.2.1
  flutter_charts: ^0.5.2
  convert: ^3.1.1
  cached_network_image: ^3.3.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  syncfusion_flutter_charts: ^25.2.7
  provider: ^6.1.2
  percent_indicator: ^4.2.3
 
  user_repository:
    path: packages/user_repository

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
          weight: 700